"""Sample Proposals Library -- a curated shelf of example proposals.

ORA Navigator coaches the *writing* of a proposal but never showed a PI what a
fundable proposal actually looks like. This module backs the /sample-proposals
page. It mixes two kinds of entries (a "hybrid" library):

  - type "pdf"  -- ORIGINAL sample proposals we authored ourselves and host as
                   downloadable PDFs (see scripts/make_sample_proposals.py).
                   Because we wrote them, there is zero copyright exposure and a
                   PI can download and read them offline. These are the most
                   useful entries for a first-timer, so they sort first.
  - type "link" -- vetted links OUT to authoritative public libraries (NSF's
                   official sample, NIH/NIAID funded apps + reviewer critiques,
                   university collections, Open Grants). We never rehost these
                   (they're copyrighted and many are index pages, not single
                   files) -- the card opens the source in a new tab.

Design (mirrors services/forms_catalog.py and main.DEFAULT_QUESTION_POOL): the
data is a static Python constant -- no DB, no embeddings, no network. The hosted
PDFs live in backend/sample_proposals/ (shipped in the Docker image) and are
served by GET /api/sample-proposals/{id}/download.

Each entry is tagged with one or more `categories` (the UI filter chips).
list_samples(category) backs the listing endpoint; get_sample(id) + pdf_path(id)
back the download endpoint. Nothing here raises.

When adding an entry: give it a unique `id` and at least one tag from CATEGORIES.
A "pdf" entry needs a `pdf` filename present in backend/sample_proposals/; a
"link" entry needs an https `url`.
"""
from __future__ import annotations

import os
from typing import Optional

# The directory holding the authored sample PDFs (committed to the repo so they
# ship inside the backend Docker image). Generated by scripts/make_sample_proposals.py.
_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF_DIR = os.path.join(_BACKEND_DIR, "sample_proposals")

# Fixed filter buckets shown as chips in the UI, in display order. An entry may
# belong to several. Keep these in sync with the `categories` values below.
CATEGORIES = ["NSF", "NIH", "NEH", "Education", "Early-career"]

# access: "free"    -> open, no login
#         "partial" -> some content behind a free account / paywall (badge it)
SAMPLE_PROPOSALS: list[dict] = [
    # === Curated: real funded proposals — direct links to official documents ==
    # Every entry opens the ACTUAL proposal PDF on the funder's or a reputable
    # university research office's own site (we never rehost). Each URL was
    # verified live (HTTP 200, application/pdf) when added. Scope: official
    # funders (NSF, NIH & institutes) + reputable university research offices.
    {
        "id": "nsf-full-funded-proposal",
        "type": "link",
        "title": "NSF — Full Funded Proposal (real example)",
        "source": "Duke University (funded NSF proposal, hosted as an example)",
        "url": "https://www.cellbio.duke.edu/sites/default/files/2022-06/NSF-Full-Proposal-Example-2010.pdf",
        "categories": ["NSF"],
        "kind": "A complete, real funded NSF proposal (PDF) — project description, "
                "references, and supporting documents",
        "access": "free",
        "why": "A real, end-to-end funded NSF proposal you can read start to finish "
               "to see how the required sections actually fit together.",
    },
    {
        "id": "nsf-career-proposal",
        "type": "link",
        "title": "NSF — CAREER Proposal (funded, early-career)",
        "source": "Carleton College / SERC (NAGT collection of successful NSF proposals)",
        "url": "https://cdn.serc.carleton.edu/files/NAGTWorkshops/earlycareer/research/desai_career_proposal.pdf",
        "categories": ["NSF", "Early-career"],
        "kind": "A complete, funded NSF CAREER proposal (PDF) — the early-career "
                "award that pairs a research plan with an education plan",
        "access": "free",
        "why": "The model to study if you're preparing an NSF CAREER award — a real "
               "funded example of the research-plus-education structure reviewers expect.",
    },
    {
        "id": "nsf-research-proposal",
        "type": "link",
        "title": "NSF — Research Proposal (funded)",
        "source": "Carleton College / SERC (NAGT collection of successful NSF proposals)",
        "url": "https://cdn.serc.carleton.edu/files/NAGTWorkshops/earlycareer/research/bracco_nsf-oce_proposal.pdf",
        "categories": ["NSF"],
        "kind": "A complete, funded standard NSF research proposal (PDF)",
        "access": "free",
        "why": "A real funded NSF research proposal — a second structural model "
               "alongside the CAREER example.",
    },
    {
        "id": "nsf-mri-proposal",
        "type": "link",
        "title": "NSF — Major Research Instrumentation (MRI) Proposal (funded)",
        "source": "Carleton College / SERC (NAGT collection of successful NSF proposals)",
        "url": "https://cdn.serc.carleton.edu/files/NAGTWorkshops/earlycareer/research/peterman_beane_proposal_2015.pdf",
        "categories": ["NSF"],
        "kind": "A complete, funded NSF MRI proposal (PDF) — a request to acquire "
                "shared research instrumentation, a different proposal type from a study",
        "access": "free",
        "why": "Shows how an equipment-acquisition proposal is justified and structured "
               "— useful when you need shared instrumentation, not a grant to run a study.",
    },
    {
        "id": "nsf-education-proposal",
        "type": "link",
        "title": "NSF — Undergraduate STEM Education (IUSE) Proposal (funded)",
        "source": "Carleton College / SERC (NAGT collection of successful NSF proposals)",
        "url": "https://cdn.serc.carleton.edu/files/NAGTWorkshops/earlycareer/research/creating_academic_community_fo.pdf",
        "categories": ["NSF"],
        "kind": "A complete, funded NSF education proposal (IUSE) (PDF) — a "
                "teaching/curriculum project rather than a research study",
        "access": "free",
        "why": "An education-focused proposal reads differently from a research one — a "
               "model if your project is about teaching, curriculum, or broadening participation.",
    },
    {
        "id": "nih-r01-funded-application",
        "type": "link",
        "title": "NIH — Funded R01 Application (real, with reviewer summary)",
        "source": "NIH — NIDCD (funded R01)",
        "url": "https://www.nidcd.nih.gov/sites/default/files/2024-07/carney-laurel-application-dc010813.pdf",
        "categories": ["NIH"],
        "kind": "A complete funded R01 application (PDF); NIDCD posts the reviewers' "
                "summary statement alongside it on nidcd.nih.gov",
        "access": "free",
        "why": "A real funded NIH R01 you can read in full — and the panel's written "
               "summary statement is posted next to it, so you see what scored well.",
    },
    {
        "id": "nih-r01-funded-application-2",
        "type": "link",
        "title": "NIH — Funded R01 Application #2 (auditory-cortex neuroscience)",
        "source": "NIH — NIDCD (funded R01)",
        "url": "https://www.nidcd.nih.gov/sites/default/files/2024-04/froemke-robert-application-2r01-dc012557-06-redacted-1.pdf",
        "categories": ["NIH"],
        "kind": "A second complete funded R01 application (PDF) in a different field; the "
                "reviewers' summary statement is posted alongside it on nidcd.nih.gov",
        "access": "free",
        "why": "A second real funded R01 in a different topic than the first — comparing "
               "two funded R01s shows what strong applications share regardless of field.",
    },
    {
        "id": "nih-r21-early-career-application",
        "type": "link",
        "title": "NIH — Funded R21 Application (Early-Career Research)",
        "source": "NIH — NIDCD (funded R21, Early-Career Research award)",
        "url": "https://www.nidcd.nih.gov/sites/default/files/2022-12/monson-ecr-r21-application.pdf",
        "categories": ["NIH", "Early-career"],
        "kind": "A complete funded R21 Early-Career Research application (PDF); the "
                "reviewers' summary statement is posted alongside it on nidcd.nih.gov",
        "access": "free",
        "why": "A real funded NIH award written by an early-career investigator — a "
               "smaller, exploratory mechanism than an R01, with the reviewer critique.",
    },

    # === NEH — funded humanities proposals (official, neh.gov) ================
    {
        "id": "neh-digital-humanities-proposal",
        "type": "link",
        "title": "NEH — Digital Humanities Proposal (funded)",
        "source": "National Endowment for the Humanities (funded application)",
        "url": "https://www.neh.gov/sites/default/files/inline-files/university_of_california_santa_cruzpreserving_cultural_software_objects_and_their_development_1.pdf",
        "categories": ["NEH"],
        "kind": "A complete funded NEH Digital Humanities grant narrative (PDF), posted by NEH "
                "as a successful application",
        "access": "free",
        "why": "A real funded humanities / digital-scholarship proposal — the model if your work "
               "is in the humanities rather than STEM.",
    },
    {
        "id": "neh-challenge-grant-proposal",
        "type": "link",
        "title": "NEH — Challenge Grant Proposal (funded)",
        "source": "National Endowment for the Humanities (funded application)",
        "url": "https://www.neh.gov/sites/default/files/inline-files/Alexandria%20Archive%20Institute%2C%20Data%20Literacy%20and%20Community%20Building%20in%20Digital%20Heritage.pdf",
        "categories": ["NEH"],
        "kind": "A complete funded NEH Challenge Grant narrative (PDF), posted by NEH as a "
                "successful application",
        "access": "free",
        "why": "A funded NEH proposal that pairs scholarship with capacity-building — useful for "
               "community-facing or infrastructure-oriented humanities projects.",
    },
    {
        "id": "neh-summer-stipends-application",
        "type": "link",
        "title": "NEH — Summer Stipends Application (funded)",
        "source": "National Endowment for the Humanities (funded application)",
        "url": "https://www.neh.gov/sites/default/files/inline-files/american_history_summer_stipends_sample_application.pdf",
        "categories": ["NEH"],
        "kind": "A complete funded NEH Summer Stipends application (PDF) — a short, single-scholar "
                "award, posted by NEH as a successful application",
        "access": "free",
        "why": "A small, self-contained funded application — an easy example to read end-to-end "
               "for a first-time humanities applicant.",
    },

    # === U.S. Dept. of Education — funded applications (official, ed.gov) =====
    {
        "id": "ed-language-resource-centers",
        "type": "link",
        "title": "Dept. of Education — Language Resource Centers Proposal (funded)",
        "source": "U.S. Department of Education (funded application, George Washington University)",
        "url": "https://www2.ed.gov/programs/iegpslrc/lrc-sampleapp-gwu.pdf",
        "categories": ["Education"],
        "kind": "A complete funded U.S. Dept. of Education grant application (PDF) — Language "
                "Resource Centers Program",
        "access": "free",
        "why": "A real funded Department of Education application — the model for education, "
               "language, and international-studies projects.",
    },
    {
        "id": "ed-strengthening-institutions",
        "type": "link",
        "title": "Dept. of Education — Strengthening Institutions / Title III (funded)",
        "source": "U.S. Department of Education (funded application)",
        "url": "https://www2.ed.gov/policy/gen/leg/foia/grants/bluemountstrength.pdf",
        "categories": ["Education"],
        "kind": "A complete funded U.S. Dept. of Education Strengthening Institutions (Title III) "
                "application (PDF; scanned)",
        "access": "free",
        "why": "A Title III institutional-capacity grant — the kind an HBCU like Morgan applies "
               "for; a directly relevant model for institutional and student-success proposals.",
    },

    # === Morgan State ORA — sample awarded proposals (home institution) =======
    # Real awarded proposals that Morgan's OWN Office of Research Administration
    # posts for its PIs (morgan.edu). Verified live; the most institution-
    # specific examples in the library.
    {
        "id": "morgan-nsf-eir-hulse",
        "type": "link",
        "title": "NSF EiR Proposal — awarded (Morgan State)",
        "source": "Morgan State University, Office of Research Administration",
        "url": "https://www.morgan.edu/Documents/ADMINISTRATION/OFFICES/ora/NSF-EiR-ProposalTomHulse.pdf",
        "categories": ["NSF", "Early-career"],
        "kind": "A complete awarded NSF EiR (HBCU Excellence in Research) proposal (PDF), posted "
                "by Morgan State ORA",
        "access": "free",
        "why": "Morgan's own example of a funded NSF HBCU-EiR award — the closest model to what a "
               "Morgan PI is actually writing.",
    },
    {
        "id": "morgan-nsf-sociology",
        "type": "link",
        "title": "NSF Awarded Proposal — Sociology (Morgan State)",
        "source": "Morgan State University, Office of Research Administration",
        "url": "https://www.morgan.edu/Documents/ADMINISTRATION/OFFICES/ora/NSF-AwardedProposalSample-sociology.pdf",
        "categories": ["NSF"],
        "kind": "A complete awarded NSF proposal in sociology (PDF), posted by Morgan State ORA",
        "access": "free",
        "why": "A funded NSF social-science proposal curated by Morgan's own ORA.",
    },
    {
        "id": "morgan-nsf-geoscience",
        "type": "link",
        "title": "NSF Awarded Proposal — Geoscience (Morgan State)",
        "source": "Morgan State University, Office of Research Administration",
        "url": "https://www.morgan.edu/Documents/ADMINISTRATION/OFFICES/ora/NSF-SampleAwardedProposal-geoscience.pdf",
        "categories": ["NSF"],
        "kind": "A complete awarded NSF proposal in geoscience (PDF), posted by Morgan State ORA",
        "access": "free",
        "why": "A funded NSF geoscience proposal curated by Morgan's own ORA.",
    },
    {
        "id": "morgan-nsf-math",
        "type": "link",
        "title": "NSF Awarded Proposal — Mathematics (Morgan State)",
        "source": "Morgan State University, Office of Research Administration",
        "url": "https://www.morgan.edu/Documents/ADMINISTRATION/OFFICES/ora/NSF-SampleAwardedProposal-math.pdf",
        "categories": ["NSF"],
        "kind": "A complete awarded NSF proposal in mathematics (PDF), posted by Morgan State ORA",
        "access": "free",
        "why": "A funded NSF mathematics proposal curated by Morgan's own ORA.",
    },
    {
        "id": "morgan-nih-r01-gordon",
        "type": "link",
        "title": "NIH R01 Awarded Application (Morgan State sample)",
        "source": "Morgan State University, Office of Research Administration",
        "url": "https://www.morgan.edu/Documents/ADMINISTRATION/OFFICES/ora/1-R01-AI121500-01A1_Funded-sample.pdf",
        "categories": ["NIH"],
        "kind": "A complete funded NIH R01 application (PDF), posted by Morgan State ORA as a sample",
        "access": "free",
        "why": "A funded NIH R01 curated by Morgan's own ORA for its PIs.",
    },
    {
        "id": "morgan-nih-r01-muir",
        "type": "link",
        "title": "NIH R01 Awarded Application #2 (Morgan State sample)",
        "source": "Morgan State University, Office of Research Administration",
        "url": "https://www.morgan.edu/Documents/ADMINISTRATION/OFFICES/ora/2-R01-AI042783-16A1_Muir_App_Sample.pdf",
        "categories": ["NIH"],
        "kind": "A second complete funded NIH R01 application (PDF), posted by Morgan State ORA as a sample",
        "access": "free",
        "why": "A second funded NIH R01 curated by Morgan's own ORA — good for comparing two funded applications.",
    },
]


def list_samples(category: Optional[str] = None) -> list[dict]:
    """Return every sample, or only those tagged with `category`.

    An empty / None / unknown category returns the full list (the page's "All"
    chip; an unknown value means a malformed request, so we degrade to "all"
    rather than show an empty page). Never raises. Returns shallow copies so
    callers can't mutate the module-level list.
    """
    if not category or category not in CATEGORIES:
        return [dict(s) for s in SAMPLE_PROPOSALS]
    return [dict(s) for s in SAMPLE_PROPOSALS if category in s["categories"]]


def categories() -> list[str]:
    """The filter buckets, in display order."""
    return list(CATEGORIES)


def get_sample(sample_id: Optional[str]) -> Optional[dict]:
    """Return the entry with this id, or None. Shallow copy."""
    if not sample_id:
        return None
    for s in SAMPLE_PROPOSALS:
        if s["id"] == sample_id:
            return dict(s)
    return None


def pdf_path(sample_id: Optional[str]) -> Optional[str]:
    """Resolve a sample id to the on-disk path of its hosted PDF, or None if the
    id is unknown, not a "pdf" entry, or the file is missing. Used by the
    download endpoint; the None cases all map to a 404."""
    s = get_sample(sample_id)
    if not s or s.get("type") != "pdf" or not s.get("pdf"):
        return None
    path = os.path.join(PDF_DIR, s["pdf"])
    return path if os.path.exists(path) else None


# ── Interest matching (deterministic; no LLM, no network) ───────────────────
import re as _re

# Words too common to signal a research interest (kept tiny + domain-aware).
_RANK_STOPWORDS = {
    "the", "a", "an", "and", "or", "of", "for", "to", "in", "on", "with", "my",
    "our", "we", "i", "is", "are", "this", "that", "new", "using", "use", "based",
    "study", "studies", "research", "project", "proposal", "develop", "developing",
    "focus", "focuses", "work", "working", "interested", "interest", "area", "field",
}


# Short acronyms that are meaningful research interests despite being <3 chars.
_KEEP_SHORT = {"ai", "ml", "ar", "vr", "ux", "ml", "ip", "qc"}


def _tokens(text: str) -> list[str]:
    """Content words (lowercased, de-duped, stopwords dropped). Keeps 3+ char
    words plus a small allowlist of meaningful 2-char acronyms (AI, ML, ...)."""
    out, seen = [], set()
    for w in _re.findall(r"[a-z][a-z\-]{1,}", (text or "").lower()):
        if w in seen or w in _RANK_STOPWORDS:
            continue
        if len(w) < 3 and w not in _KEEP_SHORT:
            continue
        seen.add(w)
        out.append(w)
    return out


def _searchable(s: dict) -> str:
    """The text we match a query against for one sample (title carries the most
    signal, so the caller weights it separately)."""
    return " ".join(str(s.get(k, "")) for k in ("source", "kind", "why")
                     ) + " " + " ".join(s.get("categories") or [])


def rank_samples(items: list[dict], query: str) -> list[dict]:
    """Reorder `items` by how well each matches the PI's free-text `query`
    (deterministic keyword overlap; title matches weigh 3x). Each matched item
    gets a `match` dict {score, terms}. Items with no match keep their original
    relative order and sort after matched ones (stable). An empty query returns
    the list unchanged (no `match` field). Never raises; pure function."""
    qt = _tokens(query)
    if not qt or not items:
        return [dict(s) for s in items]
    # Whole-word match (so "ai" doesn't match "training", "data" doesn't match
    # "database"). Compile once per query token.
    patterns = [(t, _re.compile(r"\b" + _re.escape(t) + r"\b")) for t in qt]
    ranked = []
    for idx, s in enumerate(items):
        s = dict(s)
        title_low = str(s.get("title", "")).lower()
        body_low = _searchable(s).lower()
        terms, score = [], 0
        for t, pat in patterns:
            in_title = bool(pat.search(title_low))
            in_body = bool(pat.search(body_low))
            if in_title or in_body:
                terms.append(t)
                score += (3 if in_title else 0) + (1 if in_body else 0)
        if score:
            s["match"] = {"score": score, "terms": terms}
        ranked.append((score, idx, s))
    # Highest score first; original order breaks ties (stable, authored-first).
    ranked.sort(key=lambda r: (-r[0], r[1]))
    return [s for _, _, s in ranked]
