"""Sample Proposals Library -- a curated shelf of example proposals.

ORA Navigator coaches the *writing* of a proposal but never showed a PI what a
fundable proposal actually looks like. This module backs the /sample-proposals
page. It mixes two kinds of entries (a "hybrid" library):

  - type "pdf"  -- ORIGINAL sample proposals we authored ourselves and host as
                   downloadable PDFs (see scripts/make_sample_proposals.py).
                   Because we wrote them, there is zero copyright exposure and a
                   PI can download and read them offline. These are the most
                   useful entries for a first-timer, so they sort first.
  - type "link" -- vetted links OUT to authoritative public libraries (NSF's
                   official sample, NIH/NIAID funded apps + reviewer critiques,
                   university collections, Open Grants). We never rehost these
                   (they're copyrighted and many are index pages, not single
                   files) -- the card opens the source in a new tab.

Design (mirrors services/forms_catalog.py and main.DEFAULT_QUESTION_POOL): the
data is a static Python constant -- no DB, no embeddings, no network. The hosted
PDFs live in backend/sample_proposals/ (shipped in the Docker image) and are
served by GET /api/sample-proposals/{id}/download.

Each entry is tagged with one or more `categories` (the UI filter chips).
list_samples(category) backs the listing endpoint; get_sample(id) + pdf_path(id)
back the download endpoint. Nothing here raises.

When adding an entry: give it a unique `id` and at least one tag from CATEGORIES.
A "pdf" entry needs a `pdf` filename present in backend/sample_proposals/; a
"link" entry needs an https `url`.
"""
from __future__ import annotations

import os
from typing import Optional

# The directory holding the authored sample PDFs (committed to the repo so they
# ship inside the backend Docker image). Generated by scripts/make_sample_proposals.py.
_BACKEND_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PDF_DIR = os.path.join(_BACKEND_DIR, "sample_proposals")

# Fixed filter buckets shown as chips in the UI, in display order. An entry may
# belong to several. Keep these in sync with the `categories` values below.
CATEGORIES = ["NSF", "NIH", "Foundations", "Early-career"]

# access: "free"    -> open, no login
#         "partial" -> some content behind a free account / paywall (badge it)
SAMPLE_PROPOSALS: list[dict] = [
    # === Real funded proposals — direct links to official documents =========
    # These open the actual funded proposal PDF on the funder's / a university's
    # own site (we never rehost them). Verified live when added.
    {
        "id": "nsf-full-funded-proposal",
        "type": "link",
        "title": "NSF — Full Funded Proposal (real example)",
        "source": "Duke University (funded NSF proposal, hosted as an example)",
        "url": "https://www.cellbio.duke.edu/sites/default/files/2022-06/NSF-Full-Proposal-Example-2010.pdf",
        "categories": ["NSF"],
        "kind": "A complete, real funded NSF proposal (PDF) — project description, "
                "references, and supporting documents",
        "access": "free",
        "why": "A real, end-to-end funded NSF proposal you can read start to finish "
               "to see how the required sections actually fit together.",
    },
    {
        "id": "nih-r01-funded-application",
        "type": "link",
        "title": "NIH — Funded R01 Application (real, with reviewer summary)",
        "source": "NIH — NIDCD (funded R01)",
        "url": "https://www.nidcd.nih.gov/sites/default/files/2024-07/carney-laurel-application-dc010813.pdf",
        "categories": ["NIH", "Early-career"],
        "kind": "A complete funded R01 application (PDF); NIDCD posts the reviewers' "
                "summary statement alongside it on nidcd.nih.gov",
        "access": "free",
        "why": "A real funded NIH R01 you can read in full — and the panel's written "
               "summary statement is posted next to it, so you see what scored well.",
    },

    # === Funder-published samples (links) ===================================
    {
        "id": "nsf-official-sample",
        "type": "link",
        "title": "NSF Official Sample Proposal (Cultural Anthropology)",
        "source": "National Science Foundation",
        "url": "https://www.nsf.gov/sbe/bcs/sample-proposal",
        "categories": ["NSF"],
        "kind": "Full proposal + original & revised budgets + 3 peer-review summaries",
        "access": "free",
        "why": "A rare official, end-to-end NSF example — the proposal, the "
               "budget, and the actual reviewer summaries that scored it.",
    },
    {
        "id": "niaid-sample-applications",
        "type": "link",
        "title": "NIH / NIAID Sample Applications & More",
        "source": "National Institute of Allergy and Infectious Diseases (NIH)",
        "url": "https://www.niaid.nih.gov/grants-contracts/sample-applications",
        "categories": ["NIH", "Early-career"],
        "kind": "Full funded apps — R01, R21, K-series, F31 fellowships, SBIR "
                "— most paired with the reviewers' summary statements",
        "access": "free",
        "why": "The best federal source: complete applications PLUS the written "
               "critiques, so you see both the proposal and what made it fundable.",
    },
    {
        "id": "nsf-hbcu-eir",
        "type": "link",
        "title": "NSF HBCU Excellence in Research (HBCU-EiR)",
        "source": "National Science Foundation",
        "url": "https://www.nsf.gov/funding/opportunities/hbcu-eir-historically-black-colleges-universities-excellence-research",
        "categories": ["NSF", "Early-career"],
        "kind": "Solicitation to model against (for faculty building a research program)",
        "access": "free",
        "why": "The NSF program written for HBCU faculty starting or rebuilding a "
               "research program — the solicitation your proposal should answer.",
    },

    # === University example libraries (multi-agency links) ==================
    {
        "id": "usf-proposal-samples",
        "type": "link",
        "title": "USF — Proposal Samples (Arts & Sciences)",
        "source": "University of South Florida",
        "url": "https://www.usf.edu/arts-sciences/research-scholarship/proposal-tools/proposal-samples.aspx",
        "categories": ["NSF", "NIH"],
        "kind": "Full proposals (NSF CAREER/EAGER/RAPID, NIH R01/R21, NASA, NEH) "
                "plus Data Management Plans, biosketches, and budget samples",
        "access": "free",
        "why": "One of the richest collections — covers many agencies and the "
               "individual components first-timers struggle with, all in one place.",
    },
    {
        "id": "uaf-sample-funded-proposals",
        "type": "link",
        "title": "UA Fairbanks — Sample Funded Proposals",
        "source": "University of Alaska Fairbanks",
        "url": "https://www.uaf.edu/ogca/lifecycle/3-develop/sample-funded-proposals.php",
        "categories": ["NSF", "NIH", "Foundations"],
        "kind": "Full funded proposals + summary statements across NSF, NIH, NEH, "
                "USDA, Dept. of Education, and foundations",
        "access": "free",
        "why": "A broad, multi-agency, multi-discipline hub assembled by a real "
               "research office — a good first place to browse.",
    },
    {
        "id": "northwestern-annotated-samples",
        "type": "link",
        "title": "Northwestern — Annotated Sample Grant Proposals",
        "source": "Northwestern University",
        "url": "https://undergradresearch.northwestern.edu/advising/sample-grant-proposals/",
        "categories": ["NSF", "NIH"],
        "kind": "Full funded proposals tagged by discipline AND research method "
                "(lab, fieldwork, archival, computational)",
        "access": "free",
        "why": "Annotated and method-filtered — find a model that matches HOW you "
               "do research, not just your field.",
    },
    {
        "id": "uchicago-sample-proposals",
        "type": "link",
        "title": "UChicago — Sample Proposals",
        "source": "University of Chicago Research Administration",
        "url": "https://ura.uchicago.edu/resource-library/sample-proposals",
        "categories": ["NSF", "NIH"],
        "kind": "Agency-by-agency index of full proposals — NIH (R01/R21/K/F31-"
                "Diversity/SBIR), NSF, NEH, USDA, 20+ Dept. of Education",
        "access": "free",
        "why": "A clean, well-organized index including a diversity-fellowship "
               "example that's relevant to early-career PIs.",
    },
    {
        "id": "serc-carleton-nsf",
        "type": "link",
        "title": "Carleton / SERC — Successful NSF Grant Proposals",
        "source": "Carleton College (SERC)",
        "url": "https://serc.carleton.edu/NAGTWorkshops/earlycareer/research/NSFgrants.html",
        "categories": ["NSF", "Early-career"],
        "kind": "Full funded NSF proposals — CAREER, research, REU, MRI, IUSE "
                "— concentrated in geosciences & STEM education",
        "access": "free",
        "why": "Built specifically for early-career faculty; the strongest source "
               "if you're preparing an NSF CAREER award.",
    },

    # === Foundations & general (links) ======================================
    {
        "id": "open-grants",
        "type": "link",
        "title": "Open Grants — Shared Proposals Database",
        "source": "ogrants.org",
        "url": "https://www.ogrants.org/grants-01-all",
        "categories": ["NSF", "NIH", "Foundations"],
        "kind": "~300 researcher-shared proposals (NSF, NIH, NASA, USDA, Sloan, "
                "Moore, Wellcome, CZI) — both funded AND unfunded examples",
        "access": "free",
        "why": "The largest single open catalog of real proposals across funders; "
               "the unfunded entries are instructive in their own right.",
    },
    # === Morgan State / early-career (link) =================================
    {
        "id": "morgan-ora-early-career",
        "type": "link",
        "title": "Morgan State ORA — NSF for Early-Career Researchers",
        "source": "Morgan State University, Office of Research Administration",
        "url": "https://www.morgan.edu/Documents/ADMINISTRATION/OFFICES/ora/2023%20Faculty%20Development%20Seminars/2024-02-15_PRISSEM_Early%20Career%20Morgan%20State.pdf",
        "categories": ["Early-career"],
        "kind": "Morgan's own faculty-development seminar on NSF early-career funding",
        "access": "free",
        "why": "ORA's own guidance, tailored to Morgan faculty starting out — the "
               "most institution-specific reference here.",
    },
]


def list_samples(category: Optional[str] = None) -> list[dict]:
    """Return every sample, or only those tagged with `category`.

    An empty / None / unknown category returns the full list (the page's "All"
    chip; an unknown value means a malformed request, so we degrade to "all"
    rather than show an empty page). Never raises. Returns shallow copies so
    callers can't mutate the module-level list.
    """
    if not category or category not in CATEGORIES:
        return [dict(s) for s in SAMPLE_PROPOSALS]
    return [dict(s) for s in SAMPLE_PROPOSALS if category in s["categories"]]


def categories() -> list[str]:
    """The filter buckets, in display order."""
    return list(CATEGORIES)


def get_sample(sample_id: Optional[str]) -> Optional[dict]:
    """Return the entry with this id, or None. Shallow copy."""
    if not sample_id:
        return None
    for s in SAMPLE_PROPOSALS:
        if s["id"] == sample_id:
            return dict(s)
    return None


def pdf_path(sample_id: Optional[str]) -> Optional[str]:
    """Resolve a sample id to the on-disk path of its hosted PDF, or None if the
    id is unknown, not a "pdf" entry, or the file is missing. Used by the
    download endpoint; the None cases all map to a 404."""
    s = get_sample(sample_id)
    if not s or s.get("type") != "pdf" or not s.get("pdf"):
        return None
    path = os.path.join(PDF_DIR, s["pdf"])
    return path if os.path.exists(path) else None


# ── Interest matching (deterministic; no LLM, no network) ───────────────────
import re as _re

# Words too common to signal a research interest (kept tiny + domain-aware).
_RANK_STOPWORDS = {
    "the", "a", "an", "and", "or", "of", "for", "to", "in", "on", "with", "my",
    "our", "we", "i", "is", "are", "this", "that", "new", "using", "use", "based",
    "study", "studies", "research", "project", "proposal", "develop", "developing",
    "focus", "focuses", "work", "working", "interested", "interest", "area", "field",
}


# Short acronyms that are meaningful research interests despite being <3 chars.
_KEEP_SHORT = {"ai", "ml", "ar", "vr", "ux", "ml", "ip", "qc"}


def _tokens(text: str) -> list[str]:
    """Content words (lowercased, de-duped, stopwords dropped). Keeps 3+ char
    words plus a small allowlist of meaningful 2-char acronyms (AI, ML, ...)."""
    out, seen = [], set()
    for w in _re.findall(r"[a-z][a-z\-]{1,}", (text or "").lower()):
        if w in seen or w in _RANK_STOPWORDS:
            continue
        if len(w) < 3 and w not in _KEEP_SHORT:
            continue
        seen.add(w)
        out.append(w)
    return out


def _searchable(s: dict) -> str:
    """The text we match a query against for one sample (title carries the most
    signal, so the caller weights it separately)."""
    return " ".join(str(s.get(k, "")) for k in ("source", "kind", "why")
                     ) + " " + " ".join(s.get("categories") or [])


def rank_samples(items: list[dict], query: str) -> list[dict]:
    """Reorder `items` by how well each matches the PI's free-text `query`
    (deterministic keyword overlap; title matches weigh 3x). Each matched item
    gets a `match` dict {score, terms}. Items with no match keep their original
    relative order and sort after matched ones (stable). An empty query returns
    the list unchanged (no `match` field). Never raises; pure function."""
    qt = _tokens(query)
    if not qt or not items:
        return [dict(s) for s in items]
    # Whole-word match (so "ai" doesn't match "training", "data" doesn't match
    # "database"). Compile once per query token.
    patterns = [(t, _re.compile(r"\b" + _re.escape(t) + r"\b")) for t in qt]
    ranked = []
    for idx, s in enumerate(items):
        s = dict(s)
        title_low = str(s.get("title", "")).lower()
        body_low = _searchable(s).lower()
        terms, score = [], 0
        for t, pat in patterns:
            in_title = bool(pat.search(title_low))
            in_body = bool(pat.search(body_low))
            if in_title or in_body:
                terms.append(t)
                score += (3 if in_title else 0) + (1 if in_body else 0)
        if score:
            s["match"] = {"score": score, "terms": terms}
        ranked.append((score, idx, s))
    # Highest score first; original order breaks ties (stable, authored-first).
    ranked.sort(key=lambda r: (-r[0], r[1]))
    return [s for _, _, s in ranked]
