// DraftCritiqueModal.jsx
//
// Two-step UX for the "Critique my draft" feature:
//   1. User drops a draft PDF onto a Submission they're already tracking.
//   2. Frontend POSTs the file to
//      /api/me/submissions/{id}/critique
//      -> backend reconstructs the solicitation context from the
//      submission's notes + tasks, runs Draft Critic, returns the
//      structured check list.
//   3. Modal renders each check as a row with an OK / WARN / FAIL chip
//      so the user can see in seconds where the draft falls short.
//
// Draft Critic is deterministic (no LLM), so every flagged issue is a
// real, verifiable property of the PDF -- no hallucinations to second-
// guess.

import React, { useState, useRef } from "react";
import { createPortal } from "react-dom";
import { AlertTriangle, ArrowLeft, Check, FileText, MinusCircle, X, XCircle } from "lucide-react";
import { getApiBase } from "../lib/apiBase";
import "./DraftCritiqueModal.css";

const API_BASE = getApiBase();

function authHeaders() {
  const token = localStorage.getItem("token");
  return token ? { Authorization: `Bearer ${token}` } : {};
}

const STATUS_META = {
  ok:      { label: "OK",       Icon: Check,                cls: "status-ok" },
  warn:    { label: "Warn",     Icon: AlertTriangle,  cls: "status-warn" },
  fail:    { label: "Fail",     Icon: XCircle,          cls: "status-fail" },
  skipped: { label: "Skipped",  Icon: MinusCircle,          cls: "status-skip" },
};

function StatusChip({ status }) {
  const meta = STATUS_META[status] || STATUS_META.skipped;
  const { Icon } = meta;
  return (
    <span className={`critique-status-chip ${meta.cls}`}>
      <Icon /> {meta.label}
    </span>
  );
}

// Status meta for the ADVISORY AI compliance findings (separate vocabulary
// from the deterministic checks so the two are never visually conflated).
const AI_STATUS_META = {
  addressed: { label: "Addressed", Icon: Check,         cls: "status-ok" },
  partial:   { label: "Partial",   Icon: AlertTriangle, cls: "status-warn" },
  missing:   { label: "Missing",   Icon: XCircle,       cls: "status-fail" },
  unclear:   { label: "Unclear",   Icon: MinusCircle,   cls: "status-skip" },
};

function AiStatusChip({ status }) {
  const meta = AI_STATUS_META[status] || AI_STATUS_META.unclear;
  const { Icon } = meta;
  return (
    <span className={`critique-status-chip ${meta.cls}`}>
      <Icon /> {meta.label}
    </span>
  );
}

// ADVISORY AI review. Rendered BELOW and visually subordinate to the
// deterministic checks; it can never change the verdict/counts/check rows.
function AiReviewSection({ ai }) {
  if (!ai) return null;
  const findings = ai.compliance_findings || [];
  const suggestions = ai.suggestions || [];
  return (
    <div className="critique-ai-section">
      <div className="critique-ai-header">AI Review <span className="critique-ai-badge">advisory</span></div>
      <p className="critique-ai-sub">
        Generated by AI to add context. The checks above are the source of truth —
        this section can't change them.
      </p>
      {ai.summary && <p className="critique-ai-summary">{ai.summary}</p>}
      {findings.length > 0 && (
        <div className="critique-ai-findings">
          {findings.map((f, i) => (
            <div key={i} className="critique-ai-finding">
              <div className="critique-ai-finding-head">
                <span className="critique-ai-finding-area">{f.area}</span>
                <AiStatusChip status={f.status} />
              </div>
              {f.detail && <div className="critique-ai-finding-detail">{f.detail}</div>}
              {f.evidence && (
                <div className="critique-ai-evidence" title="Verbatim quote from your draft that backs this point">
                  &ldquo;{f.evidence}&rdquo;
                </div>
              )}
            </div>
          ))}
        </div>
      )}
      {suggestions.length > 0 && (
        <div className="critique-ai-suggestions">
          <div className="critique-ai-suggestions-title">Suggestions</div>
          <ul>
            {suggestions.map((s, i) => (
              <li key={i}>
                {s.section && <strong>{s.section}: </strong>}{s.suggestion}
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

export default function DraftCritiqueModal({ submission, onClose }) {
  // step: "pick" -> "checking" -> "results"
  const [step, setStep] = useState("pick");
  const [error, setError] = useState("");
  const [result, setResult] = useState(null);
  const fileInputRef = useRef(null);

  const handleFile = async (file) => {
    if (!file) return;
    if (!file.name.toLowerCase().endsWith(".pdf")) {
      setError("Please upload a PDF file.");
      return;
    }
    if (file.size > 25 * 1024 * 1024) {
      setError("File is larger than 25 MB.");
      return;
    }

    setStep("checking");
    setError("");
    try {
      const formData = new FormData();
      formData.append("file", file);
      const res = await fetch(
        `${API_BASE}/api/me/submissions/${submission.id}/critique`,
        { method: "POST", headers: authHeaders(), body: formData },
      );
      if (!res.ok) {
        const body = await res.json().catch(() => ({}));
        throw new Error(body.detail || `${res.status} ${res.statusText}`);
      }
      const data = await res.json();
      setResult(data);
      setStep("results");
    } catch (e) {
      setError(e.message || "Couldn't critique that draft.");
      setStep("pick");
    }
  };

  const onDrop = (e) => {
    e.preventDefault();
    if (e.dataTransfer?.files?.[0]) handleFile(e.dataTransfer.files[0]);
  };
  const onDragOver = (e) => e.preventDefault();
  const triggerPicker = () => fileInputRef.current?.click();

  // Portal to <body> so the fixed overlay centers on the viewport rather than
  // inside the fixed .page-content wrapper (which would pin it to the top).
  return createPortal(
    <div className="critique-modal-overlay" onClick={onClose}>
      <div
        className="critique-modal"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="critique-modal-header">
          {step === "results" && (
            <button
              className="critique-back-btn"
              onClick={() => {
                setResult(null);
                setStep("pick");
              }}
            >
              <ArrowLeft /> Back
            </button>
          )}
          <h2>
            {step === "pick" && "Critique your draft"}
            {step === "checking" && "Checking draft..."}
            {step === "results" && "Critique results"}
          </h2>
          <button className="critique-close-btn" onClick={onClose} aria-label="Close">
            <X />
          </button>
        </div>

        {step === "pick" && (
          <>
            <p className="critique-subtitle">
              Drop your draft PDF here. We'll check it against{" "}
              <strong>{submission.title}</strong>'s solicitation
              requirements (page limit, required attachments, budget cap,
              and standard sections). No AI guessing -- every check is a
              direct read of your PDF.
            </p>

            <div
              className="critique-dropzone"
              onClick={triggerPicker}
              onDrop={onDrop}
              onDragOver={onDragOver}
              role="button"
              tabIndex={0}
            >
              <FileText className="critique-dropzone-icon" />
              <div>
                <strong>Drag your draft PDF here</strong>
                <span className="critique-dropzone-hint">
                  or click to browse (max 25 MB)
                </span>
              </div>
              <input
                ref={fileInputRef}
                type="file"
                accept="application/pdf,.pdf"
                style={{ display: "none" }}
                onChange={(e) => handleFile(e.target.files?.[0])}
              />
            </div>

            {error && <div className="critique-error">{error}</div>}
          </>
        )}

        {step === "checking" && (
          <div className="critique-loading">
            <div className="critique-spinner" />
            <p>Reading your PDF and running checks...</p>
          </div>
        )}

        {step === "results" && result && (
          <ResultsView result={result} />
        )}
      </div>
    </div>,
    document.body
  );
}

const VERDICT_CLASS = {
  ready: "verdict-ready",
  minor: "verdict-minor",
  needs_review: "verdict-warn",
  critical: "verdict-fail",
};

function VerdictBanner({ verdict }) {
  if (!verdict) return null;
  const cls = VERDICT_CLASS[verdict.level] || "verdict-minor";
  return (
    <div className={`critique-verdict ${cls}`}>
      <div className="critique-verdict-label">{verdict.label}</div>
      <div className="critique-verdict-message">{verdict.message}</div>
    </div>
  );
}

function ResultsView({ result }) {
  const c = result.critique;
  const counts = c.counts || {};
  const pageStr = c.pages === 1 ? "1 page" : `${c.pages} pages`;
  const issueStr = c.issues === 1 ? "1 issue" : `${c.issues} issues`;
  return (
    <div className="critique-results">
      <VerdictBanner verdict={c.verdict} />

      <div className="critique-summary">
        <span className="critique-summary-piece status-ok">
          <Check /> {counts.ok || 0} OK
        </span>
        <span className="critique-summary-piece status-warn">
          <AlertTriangle /> {counts.warn || 0} Warn
        </span>
        <span className="critique-summary-piece status-fail">
          <XCircle /> {counts.fail || 0} Fail
        </span>
        <span className="critique-summary-piece status-skip">
          <MinusCircle /> {counts.skipped || 0} Skipped
        </span>
      </div>

      <div className="critique-meta">
        {pageStr} &middot; sponsor {c.sponsor || "Unknown"} &middot;{" "}
        {issueStr} found
      </div>

      <div className="critique-check-list">
        {c.checks.map((check, idx) => (
          <CheckRow key={idx} check={check} />
        ))}
      </div>

      <AiReviewSection ai={c.ai_review} />

      <p className="critique-disclaimer">
        Draft Critic runs mechanical checks only -- it doesn't grade
        scientific quality or writing. Always read the solicitation
        yourself before submitting.
      </p>
    </div>
  );
}

function CheckRow({ check }) {
  return (
    <div className={`critique-check-row ${check.status}`}>
      <div className="critique-check-header">
        <div className="critique-check-name">{check.name}</div>
        <StatusChip status={check.status} />
      </div>
      {check.value && (
        <div className="critique-check-value">{check.value}</div>
      )}
      {check.detail && (
        <div className="critique-check-detail">{check.detail}</div>
      )}
      {(check.missing?.length > 0 || check.found?.length > 0) && (
        <div className="critique-check-lists">
          {check.found?.length > 0 && (
            <div>
              <strong>Found:</strong> {check.found.join(", ")}
            </div>
          )}
          {check.missing?.length > 0 && (
            <div className="critique-missing">
              <strong>Missing:</strong> {check.missing.join(", ")}
            </div>
          )}
        </div>
      )}
    </div>
  );
}
